version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    container_name: hotel_reservation_db
    restart: always
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hotel_net

networks:
  hotel_net:
    driver: bridge

volumes:
  postgres_data:
